create table users (
                       id integer generated by default as identity,
                       password varchar(255),
                       role varchar(255),
                       username varchar(255),
                       primary key (id)
)